# Generated by Django 4.2 on 2023-04-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserPet',
        ),
    ]
